gadgetSuccess:
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

homeGadgetPlotSuccess: &homeGadgetPlotSuccess
  layout: plain
  stylesheets: [-backend, gadgetPlot]
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

addGadgetSuccess:
  layout: plain
  stylesheets: [-backend]
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

editGadgetSuccess:
  layout: plain
  stylesheets: [-backend]
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype]

loginGadgetPlotSuccess:
  <<: *homeGadgetPlotSuccess

sideBannerGadgetPlotSuccess:
  <<: *homeGadgetPlotSuccess

mobileHomeGadgetPlotSuccess:
  <<: *homeGadgetPlotSuccess
