rendering: ~
security:  ~

emoji:
  class: opEmojiFilter

registerDisablePlugin:
  class: sfRegisterDisablePluginsFilter

cache:     ~
common:    ~
execution:
  class: sfOpenPNEExecutionFilter
  param:
    type: execution
