rendering: ~
security:  ~

# insert your own filters here
registerDisablePlugin:
  class: sfRegisterDisablePluginsFilter

cache:     ~
common:    ~
execution:
  class: sfOpenPNEExecutionFilter
  param:
    type: execution
