rendering: ~

enable_app:
  class: opCheckEnabledApplicationFilter

security:  ~

emoji:
  class: opEmojiFilter

cache:     ~
common:    ~
execution:
  class: sfOpenPNEExecutionFilter
  param:
    type: execution
