# openpne rules
homepage:
  url:   /
  param: { module: member, action: home }

member_index:
  url:   /member
  param: { module: member, action: home }

member_profile:
  url:   /member/:id
  param: { module: member, action: profile }
  requirements: { id: \d+ }

friend_show_image:
  url:   /friend/showImage/:id
  param: { module: friend, action: showImage }
  requirements: { id: \d+ }

community_home:
  url:   /community/:id
  param: { module: community, action: home }
  requirements: { id: \d+ }

error:
  url: /default/error
  param: { module: default, action: error }

# oauth rules
oauth_request_token:
  url:   /oauth/request_token
  param: { module: oauth, action: requestToken }

oauth_authorize_token:
  url:   /oauth/authorize
  param: { module: oauth, action: authorizeToken }

oauth_access_token:
  url:   /oauth/access_token
  param: { module: oauth, action: accessToken }

# default rules
default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
