homeSuccess:
  javascripts: [%SF_PROTOTYPE_WEB_DIR%/js/prototype, util]
  layout: layoutA
  customize:
    cautionAboutFriendPre:
      template: [friend, cautionAboutFriendPre]
      parts   : [information]
      target  : [bodyBottom]

profileSuccess:
  layout: layoutA

configSuccess:
  layout: layoutB

loginSuccess:
  layout: layoutA
