rendering: ~

enable_app:
  class: opCheckEnabledApplicationFilter
  param:
    app: mobile

security:  ~

deny:
  class: sfDenyFromNonMobileFilter

emoji:
  class: opEmojiFilter

io:
  class: sfMobileIOFilter

cache:     ~
common:    ~
execution:
  class: sfOpenPNEExecutionFilter
  param:
    type: execution
