rendering: ~
security:  ~

deny:
  class: sfDenyFromNonMobileFilter

io:
  class: sfMobileIOFilter

emoji:
  class: opEmojiFilter

cache:     ~
common:    ~
execution:
  class: sfOpenPNEExecutionFilter
  param:
    type: execution
