# openpne rules
homepage:
  url:   /
  param: { module: member, action: home }

friend_show_image:
  url:   /friend/showImage/:id
  param: { module: friend, action: showImage }
  requirements: { id: \d+ }

login:
  url: /member/login/*
  param: { module: member, action: login }

error:
  url: /default/error
  param: { module: default, action: error }
