autoload:
  plugins_application_lib:
    name:           plugins application lib
    path:           %SF_PLUGINS_DIR%/*/apps/*/lib
    recursive:      on

  plugins_application_module_lib:
    name:           plugins application module lib
    path:           %SF_PLUGINS_DIR%/*/apps/*/modules/*/lib
    recursive:      on
