propel:
  member:
    id: ~
    name: { type: varchar(64), required: true, defaultValue: "" }
    is_active: { type: boolean, required: true, defaultValue: 0 }
    created_at: ~
    updated_at: ~
    _behaviors:
      activate: {}

  member_relationship:
    id: ~
    member_id_to: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    member_id_from: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    is_friend: { type: boolean }
    is_friend_pre: { type: boolean }
    is_access_block: { type: boolean }
    _uniques:
      member_id_to_from: [ member_id_to, member_id_from ]
      member_id_from_to: [ member_id_from, member_id_to ]

  member_image:
    id: ~
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    file_id: { type: integer, required: true, foreignTable: file, foreignReference: id, onDelete: cascade }
    is_primary: { type: boolean }

  file:
    id: ~
    name: { type: varchar(64), index: unique, required: true, defaultValue: "" }
    original_filename: { type: longvarchar }
    type: { type: varchar(64), required: true, index: true, defaultValue: "" }
    created_at: ~
    updated_at: ~

  file_bin:
    file_id: { type: integer, required: true, primaryKey: true, foreignTable: file, foreignReference: id, onDelete: cascade }
    bin: { type: blob }

  profile:
    id: ~
    name: { type: varchar(64), index: unique, required: true, defaultValue: "" }
    is_required: { type: boolean, required: true, defaultValue: 0 }
    is_unique: { type: boolean, required: true, defaultValue: 0 }
    form_type: { type: varchar(32), required: true, defaultValue: "" }
    value_type: { type: varchar(32), required: true, defaultValue: "" }
    value_regexp: { type: longvarchar }
    value_min: { type: integer }
    value_max: { type: integer }
    is_disp_regist: { type: boolean, required: true, defaultValue: 0 }
    is_disp_config: { type: boolean, required: true, defaultValue: 0 }
    is_disp_search: { type: boolean, required: true, defaultValue: 0 }
    sort_order: { type: integer }

  profile_i18n:
    caption: { type: longvarchar, required: true }
    info: { type: longvarchar }

  profile_option:
    id: ~
    profile_id: { type: integer, required: true, foreignTable: profile, foreignReference: id, onDelete: cascade }
    sort_order: { type: integer }

  profile_option_i18n:
    value: { type: longvarchar }

  member_profile:
    _attributes: { treeMode: NestedSet }
    id: ~
    lft_key: { type: integer, nestedSetLeftKey: true, index: true, defaultValue: 0 }
    rht_key: { type: integer, nestedSetRightKey: true, index: true, defaultValue: 0 }
    tree_key : { type: integer, treeScopeKey: true, index: true }
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    profile_id: { type: integer, required: true, foreignTable: profile, foreignReference: id, onDelete: cascade }
    profile_option_id: { type: integer, required: false, foreignTable: profile_option, foreignReference: id, onDelete: cascade }
    value: { type: longvarchar }

  community:
    id: ~
    name: { type: varchar(64), index: unique, required: true, defaultValue: "" }
    file_id: { type: integer, required: false, foreignTable: file, foreignReference: id, onDelete: setnull }
    created_at: ~
    updated_at: ~

  community_member:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id, onDelete: cascade }
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    position: { type: varchar(32), index: true, defaultValue: "" }

  admin_user:
    id: ~
    username: { type: varchar(64), index: unique, required: true, defaultValue: "" }
    password: { type: varchar(40), required: true, defaultValue: "" }

  sns_config:
    id: ~
    name: { type: varchar(64), index: unique, required: true, defaultValue: "" }
    value: { type: longvarchar }

  member_config:
    id: ~
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    name: { type: varchar(64), required: true, defaultValue: "" }
    value: { type: longvarchar }

  community_config:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id, onDelete: cascade }
    name: { type: varchar(64), required: true, defaultValue: "" }
    value: { type: longvarchar }

  gadget:
    id: ~
    type: { type: varchar(64), required: true, index: true, defaultValue: "" }
    name: { type: varchar(64), required: true, defaultValue: "" }
    sort_order: { type: integer }

  gadget_config:
    id: ~
    gadget_id: { type: integer, foreignTable: gadget, foreignReference: id, onDelete: cascade }
    name: { type: varchar(64), required: true, defaultValue: "" }
    value: { type: longvarchar }

  navigation:
    id: ~
    type: { type: varchar(64), required: true, index: true, defaultValue: "" }
    uri: { type: longvarchar, required: true }
    sort_order: { type: integer }

  navigation_i18n:
    caption: { type: longvarchar, required: true }

  blacklist:
    id: ~
    uid: { type: varchar(32), index: unique, required: true, defaultValue: "" }
    memo: { type: longvarchar }

  invitelist:
    created_at: ~
    member_id_from: { type:integer, foreignTable: member, foreignReference: id, opDelete: cascade }
    member_id_to: { type:integer, foreignTable: member, foreignReference: id }
    mail_address: { type: longvarchar }
