propel:
  member:
    id: ~
    name: { type: varchar(64), required: true }
    is_active: { type: boolean, required: true }
    created_at: ~
    updated_at: ~

  profile:
    id: ~
    name: { type: varchar(64), index: unique, required: true }
    is_required: { type: boolean, required: true }
    is_unique: { type: boolean, required: true }
    form_type: { type: varchar(32), required: true }
    value_type: { type: varchar(32), required: true }
    value_regexp: { type: longvarchar }
    value_min: { type: integer }
    value_max: { type: integer }
    is_disp_regist: { type: boolean, required: true }
    is_disp_config: { type: boolean, required: true }
    is_disp_search: { type: boolean, required: true }
    sort_order: { type: integer }

  profile_i18n:
    caption: { type: longvarchar, required: true }
    info: { type: longvarchar }

  profile_option:
    id: ~
    profile_id: ~
    sort_order: { type: integer }

  profile_option_i18n:
    value: { type: longvarchar }

  member_profile:
    id: ~
    member_id: ~
    profile_id: ~
    profile_option_id: ~
    value: { type: longvarchar }

  friend:
    id: ~
    member_id_to: { type: integer, required: true, foreignTable: member, foreignReference: id, OnDelete: cascade }
    member_id_from: { type: integer, required: true, foreignTable: member, foreignReference: id, OnDelete: cascade }
    _uniques: 
      member_id_to_from: [ member_id_to, member_id_from ]
      member_id_from_to: [ member_id_from, member_id_to ]

  community:
    id: ~
    name: { type: varchar(64), index: unique, required: true }

  community_member:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id, OnDelete: cascade }
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, OnDelete: cascade }
    position: { type: varchar(32), index: true }

  admin_user:
    id: ~
    username: { type: varchar(64), index: unique, required: true }
    password: { type: varchar(40), required: true }

  sns_config:
    id: ~
    name: { type: varchar(64), index: unique, required: true }
    value: { type: longvarchar }

  member_config:
    id: ~
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, OnDelete: cascade }
    name: { type: varchar(64), required: true }
    value: { type: longvarchar }

  navi:
    id: ~
    type: { type: varchar(64), required: true, index: true }
    uri: { type: longvarchar }

  navi_i18n:
    caption: { type: longvarchar }
