propel:
  member:
    id: ~
    name: { type: varchar(64), required: true }
    is_active: { type: boolean, required: true }
    created_at: ~
    updated_at: ~
    _behaviors:
      activate: {}

  member_relationship:
    id: ~
    member_id_to: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    member_id_from: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    is_friend: { type: boolean }
    is_friend_pre: { type: boolean }
    is_access_block: { type: boolean }
    _uniques:
      member_id_to_from: [ member_id_to, member_id_from ]
      member_id_from_to: [ member_id_from, member_id_to ]

  member_image:
    id: ~
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    file_id: { type: integer, required: true, foreignTable: file, foreignReference: id, onDelete: cascade }
    is_primary: { type: boolean }

  file:
    id: ~
    name: { type: varchar(64), index: unique, required: true }
    original_filename: { type: longvarchar }
    bin: { type: blob }
    type: { type: varchar(64), required: true, index: true }
    created_at: ~
    updated_at: ~

  profile:
    id: ~
    name: { type: varchar(64), index: unique, required: true }
    is_required: { type: boolean, required: true }
    is_unique: { type: boolean, required: true }
    form_type: { type: varchar(32), required: true }
    value_type: { type: varchar(32), required: true }
    value_regexp: { type: longvarchar }
    value_min: { type: integer }
    value_max: { type: integer }
    is_disp_regist: { type: boolean, required: true }
    is_disp_config: { type: boolean, required: true }
    is_disp_search: { type: boolean, required: true }
    sort_order: { type: integer }

  profile_i18n:
    caption: { type: longvarchar, required: true }
    info: { type: longvarchar }

  profile_option:
    id: ~
    profile_id: { type: integer, required: true, foreignTable: profile, foreignReference: id, onDelete: cascade }
    sort_order: { type: integer }

  profile_option_i18n:
    value: { type: longvarchar }

  member_profile:
    _attributes: { treeMode: NestedSet }
    id: ~
    lft_key: { type: integer, nestedSetLeftKey: true ,index: true }
    rht_key: { type: integer, nestedSetRightKey: true ,index: true }
    tree_key : { type: integer, treeScopeKey: true ,index: true }
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    profile_id: { type: integer, required: true, foreignTable: profile, foreignReference: id, onDelete: cascade }
    profile_option_id: { type: integer, required: false, foreignTable: profile_option, foreignReference: id, onDelete: cascade }
    value: { type: longvarchar }

  community:
    id: ~
    name: { type: varchar(64), index: unique, required: true }
    file_id: { type: integer, required: false, foreignTable: file, foreignReference: id, onDelete: setnull }
    created_at: ~
    updated_at: ~
    _behaviors:
      check_privilege_belong: { class_name: CommunityMember }
      check_privilege_owner: { class_name: CommunityMember }

  community_member:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id, onDelete: cascade }
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    position: { type: varchar(32), index: true }

  admin_user:
    id: ~
    username: { type: varchar(64), index: unique, required: true }
    password: { type: varchar(40), required: true }

  sns_config:
    id: ~
    name: { type: varchar(64), index: unique, required: true }
    value: { type: longvarchar }

  member_config:
    id: ~
    member_id: { type: integer, required: true, foreignTable: member, foreignReference: id, onDelete: cascade }
    name: { type: varchar(64), required: true }
    value: { type: longvarchar }

  community_config:
    id: ~
    community_id: { type: integer, required: true, foreignTable: community, foreignReference: id, onDelete: cascade }
    name: { type: varchar(64), required: true }
    value: { type: longvarchar }

  home_widget:
    id: ~
    type: { type: varchar(64), required: true, index: true }
    name: { type: varchar(64), required: true }
    sort_order: { type: integer }

  home_widget_config:
    id: ~
    home_widget_id: { type: integer, foreignTable: home_widget, foreignReference: id, onDelete: cascade }
    name: { type: varchar(64), required: true }
    value: { type: longvarchar }

  navi:
    id: ~
    type: { type: varchar(64), required: true, index: true }
    uri: { type: longvarchar }

  navi_i18n:
    caption: { type: longvarchar }
