#api rules
api_entry:
  url:   /:module
  param: { action: entry }

api_entry_id:
  url:   /:module/:id
  param: { action: entry }
  requirements: { id: \d+ }

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default:
  url:   /:module/:action/*
