# oauth rules
oauth_request_token:
  url:   /oauth/request_token
  param: { module: oauth, action: requestToken }

oauth_authorize_token:
  url:   /oauth/authorize
  param: { module: oauth, action: authorizeToken }

oauth_access_token:
  url:   /oauth/access_token
  param: { module: oauth, action: accessToken }

# default rules
homepage:
  url:   /
  param: { module: default, action: top }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
